name: uikit
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.8.0
  vize: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
     - assets/search.png
     - assets/eye.png

  fonts:
    - family: Manrope
      fonts:
        - asset: lib/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: lib/fonts/Manrope-Light.ttf
          weight: 300
        - asset: lib/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: lib/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: lib/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: lib/fonts/Manrope-ExtraBold.ttf
          weight: 800

    - family: Playwrite
      fonts:
        - asset: lib/fonts/PlaywriteGBJGuides-Regular.ttf
          weight: 400
